name: react-s3

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Use checkout@v2
        uses: actions/checkout@v2

      - name: Step 2 - Use node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Step 3 - Install deps
        run: npm ci

      - name: Step 4 - Create a prod build
        run: npm run build

      - name: Step 5 - Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Step 6 - Deploy to S3
        run: |
          ls
          aws s3 ls
          aws s3 rb s3://rxhl-test --force
          aws s3 mb s3://rxhl-test
          aws s3 sync ./build s3://rxhl-test
